%% Phosphorylation of rhodopsin during SPR
clear all; clc; close all;

% Load the model
model = IQMmodel('Models/DM.txtbc');
%% simulation (will take a while)
time = 0:0.01:3;
model.states(stateindexIQM(model, 'R0')).initialCondition = 1; % single photon response
simulation = IQMPsimulate(model, time);

%%
R0 = simulation.statevalues(:, stateindexIQM(model, 'R0')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R0_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R0_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R0_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R0_RKpre'));
R1 = simulation.statevalues(:, stateindexIQM(model, 'R1')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R1_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R1_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R1_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R1_RKpre'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R1_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R1_Arr'));
R2 = simulation.statevalues(:, stateindexIQM(model, 'R2')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R2_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R2_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R2_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R2_RKpre'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R2_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R2_Arr'));
R3 = simulation.statevalues(:, stateindexIQM(model, 'R3')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R3_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R3_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R3_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R3_RKpre'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R3_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R3_Arr'));
R4 = simulation.statevalues(:, stateindexIQM(model, 'R4')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R4_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R4_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R4_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R4_RKpre'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R4_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R4_Arr'));
R5 = simulation.statevalues(:, stateindexIQM(model, 'R5')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R5_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R5_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R5_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R5_RKpre'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R5_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R5_Arr'));
R6 = simulation.statevalues(:, stateindexIQM(model, 'R6')) +...
    simulation.statevalues(:, stateindexIQM(model, 'R6_G'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R6_G_GTP'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R6_Gt'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R6_RKpost'))+...
    simulation.statevalues(:, stateindexIQM(model, 'R6_Arr'));

%% PUBLICATION FIGURE S7
figure(1);
subplot(1,2,1);
hold on;
pbaspect([1 1 1]);
text(0.025,0.95,'A','Units','normalized','FontSize',12);
plot(time, R0, 'r', 'LineWidth', 1);
plot(time, R1, 'Color', [0.9290, 0.6940, 0.1250], 'LineWidth', 1);
plot(time, R2, 'g', 'LineWidth', 1);
plot(time, R3, 'c', 'LineWidth', 1);
plot(time, R4, 'b', 'LineWidth', 1);
plot(time, R5, 'm', 'LineWidth', 1);
plot(time, R6, 'k', 'LineWidth', 1);
legend('R0', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6');
xlabel('time (s)');
ylabel('Species numbers');
set(gca, 'FontSize', 12);

subplot(1,2,2);
hold on;
pbaspect([1 1 1]);
text(0.025,0.95,'B','Units','normalized','FontSize',12);
plot(time, R0, 'r', 'LineWidth', 1);
plot(time, R1, 'Color', [0.9290, 0.6940, 0.1250], 'LineWidth', 1);
plot(time, R2, 'g', 'LineWidth', 1);
plot(time, R3, 'c', 'LineWidth', 1);
plot(time, R4, 'b', 'LineWidth', 1);
plot(time, R5, 'm', 'LineWidth', 1);
plot(time, R6, 'k', 'LineWidth', 1);
set(gca, 'YScale', 'log', 'FontSize', 12);
ylim([1e-25 500]);
xlabel('time (s)');
ylabel('Species numbers');
